Engineers:
  channel:
    "ENGINEERING_CHANNEL_ID"

  exclude_titles:
    - WIP
    - A/B Test
    - AB Test
    - No mergey
    - Dont merge
    - Don't merge
    - No merge

  exclude_labels:
    - paused

Frontend:
  channel:
    "FRONTEND_CHANNEL_ID"

  exclude_titles:
    - WIP
    - A/B Test
    - AB Test
    - No mergey
    - Dont merge
    - Don't merge
    - No merge

  exclude_labels:
    - paused
